spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  application:
    name: finance
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8084
  forward-headers-strategy: framework
