spring:
  datasource:
    url: jdbc:postgresql://${HOST_DB}:${FINANCE_DB_PORT}/${FINANCE_DB}
    username: ${FINANCE_USER_DB}
    password: ${FINANCE_PASSWORD_DB}

  jpa:
    hibernate:
      ddl-auto: validate

logging:
  logback:
    rollingpolicy:
      max-file-size: 50MB
      max-history: 7
      total-size-cap: 1GB